replace = {"Alamo Square":"alamosquare"
,"Anza Vista":"anzavista"
,"Aquatic Park":"aquaticpark"
,"Baja Noe":"bajanoe"
,"Balboa Park":"balboapark"
,"Balboa Terrace":"balboaterrace"
,"Bayview District":"bayviewdistrict"
,"Bayview Heights":"bayviewheights"
,"Bernal Heights":"bernalheights"
,"Bernal Heights North":"bernalheightsnorth"
,"Bernal Heights Park":"bernalheightspark"
,"Bernal Heights South":"bernalheightssouth"
,"Buena Vista Park":"buenavistapark"
,"Castro":"castro"
,"Cathedral Hill":"cathedralhill"
,"Cayuga Terrace":"cayugaterrace"
,"Central Richmond":"centralrichmond"
,"Central Sunset":"centralsunset"
,"Chinatown":"chinatown"
,"Civic Center":"civiccenter"
,"Clarendon Heights":"clarendonheights"
,"Cole Valley":"colevalley"
,"Corona Heights":"coronaheights"
,"Cow Hollow":"cowhollow"
,"Crocker-Amazon":"crocker-amazon"
,"Deco Ghetto":"decoghetto"
,"Diamond Heights":"diamondheights"
,"Dogpatch":"dogpatch"
,"Downtown":"downtown"
,"Duboce Triangle":"dubocetriangle"
,"Embarcadero":"embarcadero"
,"Excelsior":"excelsior"
,"Financial District":"financialdistrict"
,"Financial District South":"financialdistrictsouth"
,"Fisherman's Wharf":"fisherman'swharf"
,"Forest Hill":"foresthill"
,"Forest Knolls":"forestknolls"
,"Fort Mason":"fortmason"
,"French Quarter":"frenchquarter"
,"Ghirardelli Square":"ghirardellisquare"
,"Glen Park":"glenpark"
,"Golden Gate Heights":"goldengateheights"
,"Golden Gate Park":"goldengatepark"
,"Haight-Ashbury":"haight-ashbury"
,"Hayes Valley":"hayesvalley"
,"Holly Park":"hollypark"
,"Hunters Point":"hunterspoint"
,"India Basin":"indiabasin"
,"Ingleside":"ingleside"
,"Ingleside Heights":"inglesideheights"
,"Ingleside Terrace":"inglesideterrace"
,"Inner Parkside":"innerparkside"
,"Inner Richmond":"innerrichmond"
,"Inner Sunset":"innersunset"
,"Inner Sunset":"innersunset"
,"Inset":"inset"
,"Intermission":"intermission"
,"Jackson Square":"jacksonsquare"
,"Japantown":"japantown"
,"Laguna Honda":"lagunahonda"
,"Lake":"lake"
,"Lake Shore":"lakeshore"
,"Lakeside":"lakeside"
,"Laurel Heights":"laurelheights"
,"Laurel Village":"laurelvillage"
,"Little Hollywood":"littlehollywood"
,"Little Russia":"littlerussia"
,"Little Saigon":"littlesaigon"
,"Lone Mountain":"lonemountain"
,"Lower Haight":"lowerhaight"
,"Lower Nob Hill":"lowernobhill"
,"Lower Pacific Heights":"lowerpacificheights"
,"Marina District":"marinadistrict"
,"Mastro":"mastro"
,"Merced Heights":"mercedheights"
,"Merced Manor":"mercedmanor"
,"Midtown Terrace":"midtownterrace"
,"Mint Hill":"minthill"
,"Miraloma Park":"miralomapark"
,"Mission Bay":"missionbay"
,"Mission District":"missiondistrict"
,"Mission Dolores":"missiondolores"
,"Mission Terrace":"missionterrace"
,"Monterey Heights":"montereyheights"
,"Mount Davidson Manor":"mountdavidsonmanor"
,"NOMA":"noma"
,"Nob Hill":"nobhill"
,"Noe Valley":"noevalley"
,"North Beach":"northbeach"
,"North Panhandle":"northpanhandle"
,"North Waterfront":"northwaterfront"
,"Oceanview":"oceanview"
,"Outer Mission":"outermission"
,"Outer Parkside":"outerparkside"
,"Outer Richmond":"outerrichmond"
,"Outer Sunset":"outersunset"
,"Outset":"outset"
,"Pacific Heights":"pacificheights"
,"Park Merced":"parkmerced"
,"Parkside":"parkside"
,"Parnassus":"parnassus"
,"Pier 39":"pier39"
,"Pine Lake Park":"pinelakepark"
,"Polk Gulch":"polkgulch"
,"Portola":"portola"
,"Potrero Flats":"potreroflats"
,"Potrero Hill":"potrerohill"
,"Presidio":"presidio"
,"Presidio Heights":"presidioheights"
,"Presidio Terrace":"presidioterrace"
,"Richmond District":"richmonddistrict"
,"Rincon Hill":"rinconhill"
,"Russian Hill":"russianhill"
,"SOMISSPO":"somisspo"
,"Saint Francis Wood":"saintfranciswood"
,"Sea Cliff":"seacliff"
,"Sherwood Forest":"sherwoodforest"
,"Showplace Square":"showplacesquare"
,"Silver Terrace":"silverterrace"
,"South Basin":"southbasin"
,"South Beach":"southbeach"
,"South Of Market":"southofmarket"
,"South Park":"southpark"
,"St Marys Square":"stmaryssquare"
,"Stonestown":"stonestown"
,"Sunnydale":"sunnydale"
,"Sunnyside":"sunnyside"
,"Sunset District":"sunsetdistrict"
,"Sutro Heights":"sutroheights"
,"Telegraph Hill":"telegraphhill"
,"Tenderloin":"tenderloin"
,"The Hub":"thehub"
,"Transmission":"transmission"
,"Treasure Island":"treasureisland"
,"Twin Peaks":"twinpeaks"
,"Twin Peaks West":"twinpeakswest"
,"Union Square":"unionsquare"
,"Upper Market":"uppermarket"
,"Van Ness":"vanness"
,"Visitacion Valley":"visitacionvalley"
,"West Portal":"westportal"
,"West of Twin Peaks":"westoftwinpeaks"
,"Western Addition":"westernaddition"
,"Westwood Highlands":"westwoodhighlands"
,"Westwood Park":"westwoodpark"
,"Yerba Buena Island":"yerbabuenaisland"
,"Zion District":"ziondistrict"
,"Mission Deluxe" :"missiondeluxe"
,"bernalheights North": "bernalheights_n"
,"bernalheights Park": "bernalheights_p"
,"bernalheights South": "bernalheights_s"
,"Eureka Valley": "eurekavalley"
,"FiDi": "fidi"
}

# train and test unique locations

tt_word_addr =[
    "Taylor Street and Geary Street"
,"Van Ness Avenue and Turk Street"
,"Jones Street and Sutter Street"
,"Van Ness Avenue and Alice B. Toklas Place"
,"Bush Street and Taylor Street"
,"Mission Street and 25th Street"
,"23rd Street and Bartlett Street"
,"Battery Street and Halleck Street"
,"Mission Street and 7th Street"
,"Polk Street and O'Farrell Street"
,"Leavenworth Street and Ellis Street"
,"Columbus Avenue and Kearny Street"
,"Kearny Street and Geary Street"
,"Polk Street and Grove Street"
,"Geary Street and Polk Street"
,"Van Ness Avenue and Geary Boulevard"
,"Washington Street and Columbus Avenue"
,"Battery Street and California Street"
,"Jones Street and Bush Street"
,"Polk Street and Turk Street"
,"Geary Street and Hyde Street"
,"Polk Street and Willow Street"
,"Van Ness Avenue and Golden Gate Avenue"
,"Bush Street and Parking Entrance Lane"
,"Hyde Street and Golden Gate Avenue"
,"Kearny Street and Hardie Place"
,"Polk Street and Ellis Street"
,"Mission Street and 26th Street"
,"Van Ness Avenue and Bush Street"
,"Sutter Street and Mason Street"
,"Larkin Street and Geary Street"
,"Larkin Street and Sutter Street"
,"Jessie Street and New Montgomery Street"
,"Kearny Street and Broadway"
,"Kearny Street and Kearny Street"
,"Stockton Street and Union Street"
,"Washington Street and Hotaling Street"
,"Van Ness Avenue and Myrtle Street"
,"Leavenworth Street and Turk Street"
,"Jones Street and Colin Place"
,"Montgomery Street and Pacific Avenue"
,"Leavenworth Street and Eddy Street"
,"Taylor Street and O'Farrell Street"
,"Geary Street and Larkin Street"
,"Mission Street and 11th Street"
,"Montgomery Street and Montgomery Street"
,"Hyde Street and McAllister Street"
,"Taylor Street and Sutter Street"
,"Jackson Street and Van Ness Avenue"
,"Van Ness Avenue and Fell Street"
,"Geary Street and Leavenworth Street"
,"Van Ness Avenue and Washington Street"
,"Jones Street and Ellis Street"
,"Van Ness Avenue and Van Ness Avenue"
,"Montgomery Street and Bush Street"
,"Polk Street and Jackson Street"
,"Washington Street and Van Ness Avenue"
,"Stockton Street and Green Street"
,"Van Ness Avenue and Daniel Burnham Court"
,"Grove Street and Dr Carlton P Goodlett Place"
,"Columbus Avenue and Pacific Avenue"
,"Jackson Street and Polk Street"
,"Post Street and Kearny Street"
,"Mission Street and Mission Street"
,"Polk Street and Washington Street"
,"Stockton Street and Stockton Tunnel"
,"Grove Street and Larkin Street"
,"Jones Street and Jones Street"
,"Sutter Street and Powell Street"
,"Van Ness Avenue and McAllister Street"
,"Stockton Street and Jackson Street"
,"Polk Street and Olive Street"
,"Larkin Street and Eddy Street"
,"Kearny Street and Post Street"
,"Redwood Street and Polk Street"
,"Sutter Street and Sutter Street"
,"Montgomery Street and Clay Street"
,"Kearny Street and Columbus Avenue"
,"Larkin Street and Myrtle Street"
,"Larkin Street and Post Street"
,"23rd Street and Mission Street"
,"Montgomery Street and Sutter Street"
,"Geary Street and Jones Street"
,"Mason Street and Sutter Street"
,"Van Ness Avenue and Pacific Avenue"
,"Post Street and Larkin Street"
,"Mission Street and Julia Street"
,"23rd Street and South Van Ness Avenue"
,"Post Street and Meacham Place"
,"Post Street and Post Street"
,"Larkin Street and O'Farrell Street"
,"Jessie Street and Annie Street"
,"Battery Street and Washington Street"
,"Montgomery Street and Washington Street"
,"Taylor Street and Turk Street"
,"Bryant Street and Mariposa Street"
,"Polk Street and Vallejo Street"
,"Van Ness Avenue and Hemlock Street"
,"Van Ness Avenue and O'Farrell Street"
,"Jones Street and Antonio Street"
,"Van Ness Avenue and Grove Street"
,"Jones Street and Post Street"
,"Washington Street and Larkin Street"
,"Mason Street and Mason Street"
,"Redwood Street and Van Ness Avenue"
,"Polk Street and Bonita Street"
,"Larkin Street and Larkin Street"
,"Montgomery Street and Jackson Street"
,"Sutter Street and Taylor Street"
,"Pine Street and Larkin Street"
,"Larkin Street and McAllister Street"
,"Jones Street and Geary Street"
,"Bush Street and Mason Street"
,"Pine Street and Kearny Street"
,"Larkin Street and Turk Street"
,"Polk Street and Alice B. Toklas Place"
,"Van Ness Avenue and Clay Street"
,"Taylor Street and Eddy Street"
,"Larkin Street and Fulton Street"
,"Van Ness Avenue and Fern Street"
,"23rd Street and Valencia Street"
,"Montgomery Street and Commercial Street"
,"Battery Street and Pine Street"
,"Larkin Street and Cedar Street"
,"Van Ness Avenue and Hayes Street"
,"Pine Street and Van Ness Avenue"
,"Taylor Street and Bush Street"
,"Polk Street and Green Street"
,"Van Ness Avenue and Eddy Street"
,"Van Ness Avenue and Post Street"
,"Washington Street and Polk Street"
,"Van Ness Avenue and Broadway"
,"Battery Street and Merchant Street"
,"Van Ness Avenue and Austin Street"
,"Pine Street and Montgomery Street"
,"Grove Street and Van Ness Avenue"
,"Montgomery Street and Verdi Place"
,"23rd Street and Capp Street"
,"Stockton Street and Stockton Street"
,"Larkin Street and Golden Gate Avenue"
,"Geary Street and Geary Street"
,"Polk Street and Clay Street"
,"Polk Street and Dr Tom Waddell Place"
,"Pine Street and Polk Street"
,"Pine Street and Sansome Street"
,"Jones Street and Eddy Street"
,"Mission Street and 6th Street"
,"Kearny Street and Nottingham Place"
,"Polk Street and Elm Street"
,"Bryant Street and 17th Street"
,"Kearny Street and Bush Street"
,"Kearny Street and Maiden Lane"
,"Mission Street and Angelo's Alley"
,"Pine Street and Battery Street"
,"Kearny Street and Sutter Street"
,"Polk Street and Eddy Street"
,"Bush Street and Chatham Place"
,"Montgomery Street and Broadway"
]


# sensor data locations:
snsr_loc = [
"0 1ST ST"
,"200 1ST ST"
,"300 1ST ST"
,"200 2ND AVE"
,"300 2ND AVE"
,"0 2ND ST"
,"100 2ND ST"
,"200 2ND ST"
,"300 2ND ST"
,"400 2ND ST"
,"500 2ND ST"
,"600 2ND ST"
,"700 2ND ST"
,"200 3RD AVE"
,"300 3RD AVE"
,"300 3RD ST"
,"400 3RD ST"
,"500 3RD ST"
,"600 3RD ST"
,"700 3RD ST"
,"200 4TH AVE"
,"300 4TH AVE"
,"500 4TH ST"
,"600 4TH ST"
,"600 5TH ST"
,"200 7TH AVE"
,"200 9TH AVE"
,"300 9TH AVE"
,"200 10TH AVE"
,"300 10TH AVE"
,"2700 14TH AVE"
,"2800 14TH AVE"
,"2900 16TH ST"
,"3000 16TH ST"
,"3100 16TH ST"
,"3200 17TH ST"
,"3300 17TH ST"
,"3400 18TH ST"
,"3400 19TH ST"
,"3500 20TH ST"
,"3200 21ST ST"
,"3200 22ND ST"
,"3300 23RD ST"
,"0 AVILA ST"
,"0 BARTLETT ST"
,"200 BATTERY ST"
,"300 BATTERY ST"
,"400 BATTERY ST"
,"500 BATTERY ST"
,"300 BAY ST"
,"400 BAY ST"
,"500 BAY ST"
,"200 BEACH ST"
,"300 BEACH ST"
,"400 BEACH ST"
,"500 BEACH ST"
,"600 BEACH ST"
,"700 BEACH ST"
,"800 BEACH ST"
,"0 BEALE ST"
,"100 BERRY ST"
,"200 BERRY ST"
,"300 BERRY ST"
,"400 BERRY ST"
,"100 BRANNAN ST"
,"200 BRANNAN ST"
,"300 BRANNAN ST"
,"400 BRANNAN ST"
,"500 BRANNAN ST"
,"100 BRYANT ST"
,"300 BRYANT ST"
,"400 BRYANT ST"
,"500 BRYANT ST"
,"1800 BUCHANAN ST"
,"2900 BUCHANAN ST"
,"3000 BUCHANAN ST"
,"100 BUSH ST"
,"200 BUSH ST"
,"300 BUSH ST"
,"2300 CALIFORNIA ST"
,"2400 CALIFORNIA ST"
,"100 CAPP ST"
,"2000 CHESTNUT ST"
,"2100 CHESTNUT ST"
,"2200 CHESTNUT ST"
,"2300 CHESTNUT ST"
,"2400 CHESTNUT ST"
,"100 CLAY ST"
,"200 CLAY ST"
,"2400 CLAY ST"
,"2500 CLAY ST"
,"300 CLAY ST"
,"400 CLAY ST"
,"500 CLAY ST"
,"0 CLEMENT ST"
,"100 CLEMENT ST"
,"200 CLEMENT ST"
,"300 CLEMENT ST"
,"400 CLEMENT ST"
,"500 CLEMENT ST"
,"600 CLEMENT ST"
,"700 CLEMENT ST"
,"800 CLEMENT ST"
,"900 CLEMENT ST"
,"1200 COLUMBUS AVE"
,"1300 COLUMBUS AVE"
,"500 COMMERCIAL ST"
,"Lot California and Steiner"
,"0 DAVIS ST"
,"100 DAVIS ST"
,"200 DAVIS ST"
,"300 DAVIS ST"
,"600 DELANCEY ST"
,"3200 DIVISADERO ST"
,"0 DRUMM ST"
,"100 DRUMM ST"
,"200 DRUMM ST"
,"300 DRUMM ST"
,"0 EMBARCADERO NORTH"
,"100 EMBARCADERO NORTH"
,"200 EMBARCADERO NORTH"
,"0 EMBARCADERO SOUTH"
,"200 EMBARCADERO SOUTH"
,"300 EMBARCADERO SOUTH"
,"400 EMBARCADERO SOUTH"
,"500 EMBARCADERO SOUTH"
,"600 EMBARCADERO SOUTH"
,"0 FELL ST"
,"100 FELL ST"
,"200 FELL ST"
,"300 FELL ST"
,"2100 FILBERT ST"
,"2200 FILBERT ST"
,"1000 FILLMORE ST"
,"1100 FILLMORE ST"
,"1200 FILLMORE ST"
,"1300 FILLMORE ST"
,"1400 FILLMORE ST"
,"1500 FILLMORE ST"
,"1600 FILLMORE ST"
,"1700 FILLMORE ST"
,"1800 FILLMORE ST"
,"1900 FILLMORE ST"
,"2000 FILLMORE ST"
,"2100 FILLMORE ST"
,"2200 FILLMORE ST"
,"2300 FILLMORE ST"
,"2400 FILLMORE ST"
,"2900 FILLMORE ST"
,"3000 FILLMORE ST"
,"3100 FILLMORE ST"
,"3200 FILLMORE ST"
,"3300 FILLMORE ST"
,"0 FOLSOM ST"
,"500 FOLSOM ST"
,"600 FOLSOM ST"
,"100 FRANKLIN ST"
,"200 FRANKLIN ST"
,"300 FRANKLIN ST"
,"400 FRANKLIN ST"
,"500 FRANKLIN ST"
,"0 FREMONT ST"
,"200 FREMONT ST"
,"0 FRONT ST"
,"100 FRONT ST"
,"200 FRONT ST"
,"300 FRONT ST"
,"1500 GEARY BLVD"
,"1600 GEARY BLVD"
,"1700 GEARY BLVD"
,"1800 GEARY BLVD"
,"3700 GEARY BLVD"
,"3800 GEARY BLVD"
,"3900 GEARY BLVD"
,"4000 GEARY BLVD"
,"4100 GEARY BLVD"
,"4200 GEARY BLVD"
,"4300 GEARY BLVD"
,"4400 GEARY BLVD"
,"4500 GEARY BLVD"
,"4600 GEARY BLVD"
,"600 GOLDEN GATE AVE"
,"700 GOLDEN GATE AVE"
,"200 GOUGH ST"
,"300 GOUGH ST"
,"400 GOUGH ST"
,"500 GOUGH ST"
,"2100 GREENWICH ST"
,"2200 GREENWICH ST"
,"0 GROVE ST"
,"100 GROVE ST"
,"200 GROVE ST"
,"300 GROVE ST"
,"200 HALLECK ST"
,"0 HARRISON ST"
,"100 HARRISON ST"
,"500 HARRISON ST"
,"600 HARRISON ST"
,"0 HAWTHORNE ST"
,"100 HAWTHORNE ST"
,"0 HAYES ST"
,"100 HAYES ST"
,"200 HAYES ST"
,"300 HAYES ST"
,"400 HAYES ST"
,"500 HAYES ST"
,"0 HICKORY ST"
,"100 HICKORY ST"
,"0 HOFF ST"
,"0 HOWARD ST"
,"100 HOWARD ST"
,"600 HOWARD ST"
,"2800 HYDE ST"
,"0 JACKSON ST"
,"100 JACKSON ST"
,"200 JACKSON ST"
,"2300 JACKSON ST"
,"2400 JACKSON ST"
,"300 JACKSON ST"
,"400 JACKSON ST"
,"0 JEFFERSON ST"
,"100 JEFFERSON ST"
,"200 JEFFERSON ST"
,"300 JEFFERSON ST"
,"400 JEFFERSON ST"
,"500 JEFFERSON ST"
,"100 JESSIE ST"
,"2600 JONES ST"
,"2700 JONES ST"
,"2800 JONES ST"
,"0 KEARNY ST"
,"100 KEARNY ST"
,"200 KEARNY ST"
,"300 KEARNY ST"
,"400 KEARNY ST"
,"100 KING ST"
,"200 KING ST"
,"700 KING ST"
,"1500 LAGUNA ST"
,"1600 LAGUNA ST"
,"2800 LAGUNA ST"
,"2900 LAGUNA ST"
,"0 LARKIN ST"
,"100 LARKIN ST"
,"200 LARKIN ST"
,"3000 LARKIN ST"
,"2700 LEAVENWORTH ST"
,"2800 LEAVENWORTH ST"
,"0 LECH WALESA ST"
,"2000 LOMBARD ST"
,"2100 LOMBARD ST"
,"2200 LOMBARD ST"
,"2300 LOMBARD ST"
,"2400 LOMBARD ST"
,"0 MAIN ST"
,"300 MAIN ST"
,"0 MALLORCA WAY"
,"0 MARKET ST"
,"2300 MASON ST"
,"2400 MASON ST"
,"2500 MASON ST"
,"2600 MASON ST"
,"300 MCALLISTER ST"
,"400 MCALLISTER ST"
,"500 MCALLISTER ST"
,"400 MERCHANT ST"
,"100 MINNA ST"
,"0 MISSION ST"
,"100 MISSION ST"
,"2000 MISSION ST"
,"2100 MISSION ST"
,"2200 MISSION ST"
,"2300 MISSION ST"
,"2400 MISSION ST"
,"2500 MISSION ST"
,"2600 MISSION ST"
,"2700 MISSION ST"
,"600 MISSION ST"
,"0 MONTGOMERY ST"
,"100 MONTGOMERY ST"
,"200 MONTGOMERY ST"
,"300 MONTGOMERY ST"
,"400 MONTGOMERY ST"
,"500 MONTGOMERY ST"
,"600 MONTGOMERY ST"
,"700 MONTGOMERY ST"
,"100 NATOMA ST"
,"0 NEW MONTGOMERY ST"
,"100 NEW MONTGOMERY ST"
,"100 NORTH POINT ST"
,"200 NORTH POINT ST"
,"300 NORTH POINT ST"
,"400 NORTH POINT ST"
,"500 NORTH POINT ST"
,"600 NORTH POINT ST"
,"900 NORTH POINT ST"
,"0 OAK ST"
,"100 OAK ST"
,"2700 OCTAVIA ST"
,"2800 OCTAVIA ST"
,"3200 PIERCE ST"
,"3300 PIERCE ST"
,"0 PINE ST"
,"100 PINE ST"
,"200 PINE ST"
,"2300 PINE ST"
,"300 PINE ST"
,"400 PINE ST"
,"100 PIXLEY ST"
,"200 PIXLEY ST"
,"0 POLK ST"
,"100 POLK ST"
,"200 POLK ST"
,"300 POLK ST"
,"3100 POLK ST"
,"0 POST ST"
,"1600 POST ST"
,"1700 POST ST"
,"1800 POST ST"
,"1900 POST ST"
,"2300 POWELL ST"
,"2400 POWELL ST"
,"100 REDWOOD ST"
,"300 RITCH ST"
,"100 SACRAMENTO ST"
,"200 SACRAMENTO ST"
,"2400 SACRAMENTO ST"
,"2500 SACRAMENTO ST"
,"300 SACRAMENTO ST"
,"400 SACRAMENTO ST"
,"500 SACRAMENTO ST"
,"0 SANSOME ST"
,"100 SANSOME ST"
,"200 SANSOME ST"
,"300 SANSOME ST"
,"400 SANSOME ST"
,"500 SANSOME ST"
,"600 SANSOME ST"
,"3200 SCOTT ST"
,"3300 SCOTT ST"
,"0 SOUTH PARK"
,"100 SOUTH PARK"
,"0 SPEAR ST"
,"100 SPEAR ST"
,"200 SPEAR ST"
,"300 SPEAR ST"
,"400 SPEAR ST"
,"1500 STEINER ST"
,"3300 STEINER ST"
,"0 STEUART ST"
,"100 STEUART ST"
,"200 STEUART ST"
,"0 STEVENSON ST"
,"2300 STOCKTON ST"
,"0 SUTTER ST"
,"100 SUTTER ST"
,"1800 SUTTER ST"
,"2000 SUTTER ST"
,"2500 TAYLOR ST"
,"2600 TAYLOR ST"
,"2700 TAYLOR ST"
,"100 TEHAMA ST"
,"0 TOWNSEND ST"
,"100 TOWNSEND ST"
,"200 TOWNSEND ST"
,"300 TOWNSEND ST"
,"1700 UNION ST"
,"1800 UNION ST"
,"1900 UNION ST"
,"2000 UNION ST"
,"2100 UNION ST"
,"2200 UNION ST"
,"1000 VALENCIA ST"
,"1100 VALENCIA ST"
,"1200 VALENCIA ST"
,"400 VALENCIA ST"
,"500 VALENCIA ST"
,"600 VALENCIA ST"
,"700 VALENCIA ST"
,"800 VALENCIA ST"
,"900 VALENCIA ST"
,"0 VAN NESS AVE"
,"100 VAN NESS AVE"
,"200 VAN NESS AVE"
,"300 VAN NESS AVE"
,"400 VAN NESS AVE"
,"500 VAN NESS AVE"
,"0 VICENTE ST"
,"100 VICENTE ST"
,"0 WASHINGTON ST"
,"100 WASHINGTON ST"
,"200 WASHINGTON ST"
,"2400 WASHINGTON ST"
,"2500 WASHINGTON ST"
,"300 WASHINGTON ST"
,"400 WASHINGTON ST"
,"500 WASHINGTON ST"
,"1500 WEBSTER ST"
,"1600 WEBSTER ST"
,"2100 WEBSTER ST"
,"2200 WEBSTER ST"
,"2800 WEBSTER ST"
,"2900 WEBSTER ST"
,"0 WEST PORTAL AVE"
,"100 WEST PORTAL AVE"
,"200 WEST PORTAL AVE"
,"300 WEST PORTAL AVE"
]